### PR TITLE
Fix for reset/panic overriding the user's stop take 2

### LINKED ISSUE #86: Cannot stop simulator with program containing reset in tight loop
```
from microbit import *
import machine
import random

while True:
    num = random.randint(1, 7)
    display.show(num)
    sleep(10) # works ok for me with 20ms
    machine.reset()
```

It stops OK with 20ms of delay or if you remove machine.reset().

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
A reprise of #88 but without the unfortunate introduction of #90.

Needs careful testing.

Closes #86

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
The delta vs last time is in https://github.com/microbit-foundation/micropython-microbit-v2-simulator/pull/91/commits/556c80b81a22feaea863169fb61c7f7043109e4d

**Comment by microbit-matt-hillsdon** [comment]
You can try it out at 
https://review-python-editor-v3.microbit.org/user-stop-wins/ and
https://review-python-simulator.usermbit.org/user-stop-wins/demo.html

Test programs on #86.

**Review by microbit-robert — APPROVED** [review]
LGTM. Still fixes linked issues without introducing the restart issue of the last attempt.

**Comment by microbit-matt-hillsdon** [comment]
This seems to be working well now. I've asked for some review testing from other Foundation folks so will hold off from merging until I hear back.

**Comment by microbit-matt-hillsdon** [comment]
Found #93 reviewing this but it seems to be an unrelated issue.

**Pull request merged**
